// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PdaAnalytics.Data;

#nullable disable

namespace PdaAnalytics.Data.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260224175200_AddWebUsers")]
    partial class AddWebUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.Chat", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceInstance")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_instance");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.HasKey("SourceId", "SourceInstance");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.ChatParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("account_source_id");

                    b.Property<string>("AccountSourceInstance")
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ChatSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_source_id");

                    b.Property<int>("ContactAccountSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("contact_account_source_id");

                    b.Property<string>("ContactAccountSourceInstance")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceInstance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_instance");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountSourceId", "AccountSourceInstance");

                    b.HasIndex("ChatSourceId", "SourceInstance");

                    b.HasIndex("ContactAccountSourceId", "ContactAccountSourceInstance");

                    b.HasIndex("ChatSourceId", "AccountSourceId", "SourceInstance")
                        .IsUnique()
                        .HasDatabaseName("uq_chat_participants");

                    b.ToTable("chat_participants", (string)null);
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.Faction", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceInstance")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_instance");

                    b.Property<long>("Color")
                        .HasColumnType("bigint")
                        .HasColumnName("color");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("SourceId", "SourceInstance");

                    b.ToTable("factions", (string)null);
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.FactionMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("FactionSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("faction_source_id");

                    b.Property<string>("MemberSteamId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("member_steam_id");

                    b.Property<int>("RankId")
                        .HasColumnType("integer")
                        .HasColumnName("rank_id");

                    b.Property<string>("SourceInstance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_instance");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("FactionSourceId", "SourceInstance");

                    b.HasIndex("MemberSteamId", "SourceInstance");

                    b.HasIndex("MemberSteamId", "FactionSourceId", "SourceInstance")
                        .IsUnique()
                        .HasDatabaseName("uq_faction_memberships");

                    b.ToTable("faction_memberships", (string)null);
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.MessageDenormalized", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text")
                        .HasColumnName("attachments");

                    b.Property<string>("ChatName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("chat_name");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("chat_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("ReceiverAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_account_id");

                    b.Property<string>("ReceiverLogin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receiver_login");

                    b.Property<string>("ReceiverNickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receiver_nickname");

                    b.Property<string>("ReceiverSteamId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("receiver_steam_id");

                    b.Property<int>("SenderAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_account_id");

                    b.Property<string>("SenderLogin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sender_login");

                    b.Property<string>("SenderNickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sender_nickname");

                    b.Property<string>("SenderSteamId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sender_steam_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("SourceChatId")
                        .HasColumnType("integer")
                        .HasColumnName("source_chat_id");

                    b.Property<string>("SourceInstance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_instance");

                    b.Property<int>("SourceMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("source_message_id");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("ix_messages_sent_at");

                    b.HasIndex("ReceiverSteamId", "SentAt")
                        .HasDatabaseName("ix_messages_receiver_date");

                    b.HasIndex("SourceMessageId", "SourceInstance")
                        .IsUnique()
                        .HasDatabaseName("uq_messages_source");

                    b.HasIndex("SenderSteamId", "ReceiverSteamId", "SentAt")
                        .HasDatabaseName("ix_messages_sender_receiver_date");

                    b.HasIndex("SourceChatId", "SourceInstance", "SentAt")
                        .HasDatabaseName("ix_messages_chat_date");

                    b.ToTable("messages_denormalized", (string)null);
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.PdaAccount", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceInstance")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_instance");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("steam_id");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("SourceId", "SourceInstance");

                    b.HasIndex("Login")
                        .HasDatabaseName("ix_pda_accounts_login");

                    b.HasIndex("SteamId")
                        .HasDatabaseName("ix_pda_accounts_steam_id");

                    b.HasIndex("SteamId", "SourceInstance");

                    b.ToTable("pda_accounts", (string)null);
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.Player", b =>
                {
                    b.Property<string>("SteamId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("steam_id");

                    b.Property<string>("SourceInstance")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_instance");

                    b.Property<DateTime>("LastLogonDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_logon_date");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("SteamId", "SourceInstance");

                    b.HasIndex("Nickname")
                        .HasDatabaseName("ix_players_nickname");

                    b.HasIndex("SteamId")
                        .HasDatabaseName("ix_players_steam_id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("instance_name");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<long>("LastSyncedId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_synced_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("table_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InstanceName", "TableName")
                        .IsUnique()
                        .HasDatabaseName("uq_sync_state_instance_table");

                    b.ToTable("sync_states", (string)null);
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.WebUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_web_users_username");

                    b.ToTable("web_users", (string)null);
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.ChatParticipant", b =>
                {
                    b.HasOne("PdaAnalytics.Domain.Entities.PdaAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountSourceId", "AccountSourceInstance");

                    b.HasOne("PdaAnalytics.Domain.Entities.Chat", "Chat")
                        .WithMany("Participants")
                        .HasForeignKey("ChatSourceId", "SourceInstance")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PdaAnalytics.Domain.Entities.PdaAccount", "ContactAccount")
                        .WithMany()
                        .HasForeignKey("ContactAccountSourceId", "ContactAccountSourceInstance");

                    b.Navigation("Account");

                    b.Navigation("Chat");

                    b.Navigation("ContactAccount");
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.FactionMembership", b =>
                {
                    b.HasOne("PdaAnalytics.Domain.Entities.Faction", "Faction")
                        .WithMany("Members")
                        .HasForeignKey("FactionSourceId", "SourceInstance")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PdaAnalytics.Domain.Entities.Player", "Player")
                        .WithMany("FactionMemberships")
                        .HasForeignKey("MemberSteamId", "SourceInstance")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.PdaAccount", b =>
                {
                    b.HasOne("PdaAnalytics.Domain.Entities.Player", "Player")
                        .WithMany("PdaAccounts")
                        .HasForeignKey("SteamId", "SourceInstance")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.Chat", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.Faction", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PdaAnalytics.Domain.Entities.Player", b =>
                {
                    b.Navigation("FactionMemberships");

                    b.Navigation("PdaAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
